enum PostKind {
  club,
  user;

  static PostKind parse(String? raw) => switch (raw?.toUpperCase()) {
        'CLUB' => PostKind.club,
        'USER' => PostKind.user,
        _ => PostKind.club,
      };

  String get wire => switch (this) {
        PostKind.club => 'club',
        PostKind.user => 'user',
      };
}

enum PostAttachmentKind {
  image,
  activity,
  challengeProgress,
  unknown;

  static PostAttachmentKind parse(String? raw) => switch (raw?.toUpperCase()) {
        'IMAGE' => PostAttachmentKind.image,
        'ACTIVITY' => PostAttachmentKind.activity,
        'CHALLENGE_PROGRESS' => PostAttachmentKind.challengeProgress,
        _ => PostAttachmentKind.unknown,
      };

  String get wire => switch (this) {
        PostAttachmentKind.image => 'IMAGE',
        PostAttachmentKind.activity => 'ACTIVITY',
        PostAttachmentKind.challengeProgress => 'CHALLENGE_PROGRESS',
        PostAttachmentKind.unknown => 'IMAGE',
      };
}

/// One attachment on a post — image or activity card.
class PostAttachment {
  final String id;
  final PostAttachmentKind kind;
  final int sortOrder;

  /// Non-null when [kind] == [PostAttachmentKind.image].
  /// 7-day signed GCS GET URL generated by the server.
  final String? displayUrl;

  /// Non-null when [kind] == [PostAttachmentKind.activity] or
  /// [PostAttachmentKind.challengeProgress].
  final String? refId;

  const PostAttachment({
    required this.id,
    required this.kind,
    required this.sortOrder,
    this.displayUrl,
    this.refId,
  });

  factory PostAttachment.fromJson(Map<String, dynamic> json) {
    return PostAttachment(
      id: json['id'] as String,
      kind: PostAttachmentKind.parse(json['kind'] as String?),
      sortOrder: json['sort_order'] as int? ?? 0,
      displayUrl: json['display_url'] as String?,
      refId: json['ref_id'] as String?,
    );
  }
}

/// One attachment slot in a create-post request.
/// For IMAGE: set [tempMediaId]. For ACTIVITY: set [refId].
class PostAttachmentRequest {
  final PostAttachmentKind kind;
  final String? tempMediaId;
  final String? refId;

  const PostAttachmentRequest({
    required this.kind,
    this.tempMediaId,
    this.refId,
  });

  Map<String, dynamic> toJson() => {
        'kind': kind.wire,
        if (tempMediaId != null) 'temp_media_id': tempMediaId,
        if (refId != null) 'ref_id': refId,
      };
}

/// Unified post payload returned by feed, per-club, and per-author
/// endpoints.
class Post {
  final String id;
  final PostKind kind;

  final String authorId;
  final String authorName;
  final String authorEmail;
  final String? authorAvatarUrl;

  final String? clubId;
  final String? clubName;

  final String content;
  final List<PostAttachment> attachments;

  final int likes;
  final int dislikes;
  final int commentCount;

  final bool? userLiked;
  final String createdAt;

  const Post({
    required this.id,
    required this.kind,
    required this.authorId,
    required this.authorName,
    required this.authorEmail,
    this.authorAvatarUrl,
    this.clubId,
    this.clubName,
    required this.content,
    this.attachments = const [],
    required this.likes,
    required this.dislikes,
    required this.commentCount,
    this.userLiked,
    required this.createdAt,
  });

  factory Post.fromJson(Map<String, dynamic> json) {
    final rawAttachments = json['attachments'] as List<dynamic>? ?? [];
    return Post(
      id: json['id'] as String,
      kind: PostKind.parse(json['kind'] as String?),
      authorId: json['author_id'] as String,
      authorName: json['author_name'] ?? '',
      authorEmail: json['author_email'] ?? '',
      authorAvatarUrl: json['author_avatar_url'] as String?,
      clubId: json['club_id'] as String?,
      clubName: json['club_name'] as String?,
      content: json['content'] ?? '',
      attachments: rawAttachments
          .map((e) => PostAttachment.fromJson(e as Map<String, dynamic>))
          .toList(),
      likes: json['likes'] ?? 0,
      dislikes: json['dislikes'] ?? 0,
      commentCount: json['comment_count'] ?? 0,
      userLiked: json['user_liked'] as bool?,
      createdAt: json['created_at'] ?? '',
    );
  }
}

class Comment {
  final String id;
  final String authorName;
  final String authorEmail;
  final String content;
  final String createdAt;

  const Comment({
    required this.id,
    required this.authorName,
    required this.authorEmail,
    required this.content,
    required this.createdAt,
  });

  factory Comment.fromJson(Map<String, dynamic> json) {
    return Comment(
      id: json['id'] as String,
      authorName: json['author_name'] ?? '',
      authorEmail: json['author_email'] ?? '',
      content: json['content'] ?? '',
      createdAt: json['created_at'] ?? '',
    );
  }
}
